---
- name: Provision my machine with goodies
  hosts: localhost

  tasks:
  - name: vim
    apt:
      name: vim
  - name: emacs
    apt:
      name: emacs

  - name: curl
    apt:
      name: curl
  - name: tree
    apt:
      name: tree
  - name: xclip
    apt:
      name: xclip
  - name: jq
    apt:
      name: jq

  - name: git
    apt:
      name: git
  - name: xmonad
    apt:
      name: xmonad
  - name: xmobar
    apt:
      name: xmobar
  - name: xmobar
    apt:
      name: xmobar
  - name: dmenu
    apt:
      name: dmenu
  - name: zsh
    apt:
      name: zsh
  - name: feh
    apt:
      name: feh

  # Really fast search: ag > awk > grep (Runtimes)
  # @see https://github.com/ggreer/the_silver_searcher
  - name: The silver searcher
    apt:
      name: silversearcher-ag

  - name: autojump
    apt:
      name: autojump
  - name: cowsay
    apt:
      name: cowsay

  - name: docker
    apt:
      name: docker.io

  - name: Chromium
    apt:
      name: chromium-browser

  - name: Pulse audio video control
    apt:
      name: pavucontrol

  # Screen recording
  - name: Kazam
    apt:
      name: kazam
  # Screenshots
  - name: flameshot
    apt:
      name: flameshot

  # Play videos
  - name: VLC
    apt:
      name: vlc

  # Secret management
  - name: Last pass
    apt:
      name: lastpass-cli

  # xfreerdp
  - name: Remote desktop
    apt:
      name: freerdp2-x11

  # Python formatter
  - name: Yapf
    apt:
      name: yapf3
