---
- name: Provision my machine with goodies
  hosts: localhost

  tasks:
  - name: vim
    apt:
      name: vim
  - name: emacs
    apt:
      name: emacs
  - name: git
    apt:
      name: git
  - name: xmonad
    apt:
      name: xmonad
  - name: xmobar
    apt:
      name: xmobar
  - name: xmobar
    apt:
      name: xmobar
  - name: dmenu
    apt:
      name: dmenu
  - name: zsh
    apt:
      name: zsh
  - name: feh
    apt:
      name: feh

  # Really fast search: ag > awk > grep (Runtimes)
  # @see https://github.com/ggreer/the_silver_searcher
  - name: The silver searcher
    apt:
      name: silversearcher-ag

  - name: autojump
    apt:
      name: autojump
  - name: cowsay
    apt:
      name: cowsay
