;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		c-beginning-of-statement
		c-electric-brace
		c-electric-colon
		c-electric-delete-forward
		c-electric-paren
		c-electric-pound
		c-electric-semi&comma
		c-end-of-statement
		comint-delchar-or-maybe-eof
		dabbrev-expand
		end-of-buffer
		evil-backward-char
		evil-change
		evil-delete
		evil-delete-backward-word
		evil-insert
		evil-next-line
		evil-normal-state
		evil-open-above
		evil-previous-line
		evil-scroll-line-down
		forward-sentence
		god-local-mode
		god-mode-self-insert
		indent-for-tab-command
		indent-new-comment-line
		kill-region
		markdown-exdent-or-delete
		org-beginning-of-line
		org-end-of-line
		org-kill-line
		org-open-line
		org-self-insert-command
		org-yank
		paredit-kill
		previous-buffer
		query-replace
		wdired-finish-edit
		))

(setq mc/cmds-to-run-once
      '(
		compile
		eval-defun
		paredit-open-round
		))
