---
- name: Provision linux machine with goodies
  hosts: localhost

  tasks:
  - name: gui
    package:
      name:
        - xmonad
        - xmobar
        - dmenu

  - name: security
    package:
      name:
        # - mcrypt
        # - x11-ssh-askpass
        - xscreensaver

  - name: Sound
    package:
      name:
        - alsa-utils
        - pulseaudio
        - pavucontrol
        # arch
        # - pulseaudio-alsa

  - name: Bluetooth
    package:
      name:
        - bluetooth
        - bluez
        - blueman
        # arch
        # - bluez-utils
        # - pulseaudio-bluetooth

  # # backlight
  # - name: Power utils (Keyboard backlight)
  #   package:
  #     name:
  #       - upower
  #       - python-dbus

  - name: Multiple monitors
    package:
      name:
        - arandr

  - name: Pdf / screenshot / images
    package:
      name:
        - flameshot
        - eog
        - evince
        - pdftk

  - name: Docker
    package:
      name:
        - docker
        - docker-compose

  - name: Terminals and tools
    package:
      name:
        - kitty
        - exa
        - parallel
        - unzip
        - xclip
        - jq
        # - ngrok
        - net-tools
        - dunst

  - name: System
    package:
      name:
        - lsof
        - inotify-tools
        - xinput

  # - name: Misc
  #   package:
  #     name:
  #       - noto-fonts-emoji
