---
- name: Provision arch linux machine with goodies
  hosts: localhost
  # roles:
  # - kewlfft.aur

  tasks:
  - name: gui
    pacman:
      name:
        - xmonad
        - xmobar
        - dmenu

  - name: security
    pacman:
      name:
        - mcrypt
        - arch-audit
        - x11-ssh-askpass

  - name: Sound
    pacman:
      name:
        - alsa-utils
        - pulseaudio
        - pulseaudio-alsa
        - pavucontrol

  - name: Bluetooth
    pacman:
      name:
        - bluez
        - bluez-utils
        - pulseaudio-bluetooth
        - blueman

  # backlight
  - name: Power utils (Keyboard backlight)
    pacman:
      name:
        - upower
        - python-dbus

  - name: Multiple monitors
    pacman:
      name:
        - arandr

  - name: Pdf / screenshot / images
    pacman:
      name:
        - flameshot
        - eog
        - evince
        - pdftk

  - name: Slack
    pacman:
      name:
        - slack-desktop

  - name: Docker
    pacman:
      name:
        - docker
        - docker-compose

  - name: Terminals and tools
    pacman:
      name:
        - kitty
        - exa
        - parallel
        - unzip
        - xclip
        - jq
        - ngrok
        - net-tools

  - name: System
    pacman:
      name:
        - lsof
        - inotify-tools

  - name: Misc
    pacman:
      name:
        - noto-fonts-emoji

  # TODO: fix issue with roles
  # - aur: name=autojump
  #   become: true
  #   become_user: "{{ user.name }}"



  # # Secret management
  # - name: Last pass
  #   pacman:
  #     name: lastpass-cli

  # # xfreerdp
  # - name: Remote desktop
  #   pacman:
  #     name: freerdp2-x11

  # - name: graphviz
  #   pacman:
  #     name: graphviz

  # - name: rlwrap
  #   pacman:
  #     name: rlwrap

  # - name: openjdk-8-jre
  #   pacman:
  #     name: openjdk-8-jre
