---
- name: Testing provisioning of libraries
  hosts: localhost
  roles:
  - kewlfft.aur

  tasks:

  - name: Terminal and tools
    pacman:
      name:
        - kitty
        - exa
        - parallel
        - unzip
        - xclip
        - jq

  # - aur: name=autojump
  #   become: true
  #   become_user: "{{ user.name }}"
