#!/bin/bash

# Usage
# blob ci_$CI_IID/Enriched/model.json

. "$(dirname "$(realpath "$0")")"/blob-common

if [ -z "$NAME" ]; then
    echo "Error :: No blob name supplied" && exit
fi

FILE=$ROOT_DIR/$NAME
DIR=`dirname $FILE`
mkdir -p $DIR

az storage blob download --container-name $BLOB_CONTAINER_NAME --name $NAME --file $FILE --output none && echo $FILE

[ $? -eq 0 ] || echo Unable to download blob: $NAME
