#!/bin/bash

# az storage blob list --container-name $CONTAINER_NAME --prefix $PREFIX$INSTANCE | jq ".[] | [.name, .properties.creationTime, .properties.lastModified]" -r

# Get all the blobs for the instance:
# $ list
# Get all the blobs with a prefix:
# $ list ci_$INSTANCE/Enriched

PREFIX=${1:-$BLOB_PREFIX}
echo "Prefix    : $PREFIX"
echo "Container : $BLOB_CONTAINER_NAME"
az storage blob list --container-name $BLOB_CONTAINER_NAME --prefix $PREFIX | jq ".[].name" -r

