#!/bin/bash

# Usage
# blob ci_$CI_IID/Enriched/model.json

. "$(dirname "$(realpath "$0")")"/blob-common

FILE=/tmp/blob-contents.xxx
az storage blob download --container-name $BLOB_CONTAINER_NAME --name $1 --file $FILE --output none && cat $FILE
