#!/bin/bash

# az storage blob list --container-name $CONTAINER_NAME --prefix $PREFIX$INSTANCE | jq ".[] | [.name, .properties.creationTime, .properties.lastModified]" -r

# Get all the blobs for the instance:
# $ list
# Get all the blobs with a prefix:
# $ list ci_$INSTANCE/Enriched

. "$(dirname "$(realpath "$0")")"/blob-common

# --num-results 100 \

az storage blob list \
   --container-name $BLOB_CONTAINER_NAME \
   --prefix $PREFIX \
    | jq ".[].name" -r

